### ISSUE TITLE
Finance: show total expense of a day

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/wallora.com#108]
This is a
[ ] bug
[x] feature request
[ ] documentation change
[ ] build/deploy enhancement request

Description:
* Show total expense of each day in date header
* Round of decimal values

![image](https://user-images.githubusercontent.com/195256/121768487-15611800-cb7c-11eb-89db-90120f0f450a.png)

**Comment by rajakvk** [comment]
@souvikbasu As discussed in Slack, I will start working on this feature. Please assign issue on my name.
