### ISSUE TITLE
App: Create Master-Details layout for the app with a vertical menu

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/wallora.com#59]
This is a
[ ] bug
[x] feature request
[ ] documentation change
[ ] build/deploy enhancement request

Description:
Once the user signs in, the app will show as a 2 column layout. The first column will be a menu bar on the left side (similar to the activity bar in VS Code) and the second column will show the details panel shown based on the menu selected on the left menu

Responsiveness:
The app will have two modes: landscape (for laptop) and portrait (for mobile screen)
For mobile screen, the menu will show as tabs at the bottom 

Icons:
For now, use the same icons as in wallora.com. We will replace these with a new set of icons. Use sprite for showing the icons, similar to that done for home page footer
![image](https://user-images.githubusercontent.com/195256/118354202-c4c7b200-b51e-11eb-8855-4d36411a1f7b.png)

**Comment by priyankajayaswal** [comment]
On login, we would want to update the header bg to white and keep it same as the old website?
What is the expected width of the first column?
I might pick this up once questions are clarified and no one has yet picked it up.

**Comment by souvikbasu** [comment]
we can maintain the current home page header color as the tool bar bg color
