### ISSUE TITLE
Dashboard: Major Expenses planned in next 6 months

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/wallora.com#62]
This is a
[ ] bug
[x] feature request
[ ] documentation change
[ ] build/deploy enhancement request

Description:
Show the section "Major Expenses planned in next 6 months" in Dashboard same as in waloraa.com

![image](https://user-images.githubusercontent.com/195256/118354926-4705a580-b522-11eb-8805-263d1aef107e.png)

Chart:
Use same chart lib as used for #60 

API:
Use Apollo GraphQL client and create query to fetch data from API:
https://wallora.com/api/stats/total-planned-amount-workitemwise?startmonth=202105&endmonth=202105
https://wallora.com/api/stats/total-actual-amount-workitemwise?startdate=20210501&enddate=20210531

**Comment by priyankajayaswal** [comment]
How is actual amount used? this is forecast right. @souvikbasu
