### ISSUE TITLE
Auth: Google Sign in

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/wallora.com#63]
This is a
[ ] bug
[x] feature request
[ ] documentation change
[ ] build/deploy enhancement request

Description:
Add support for Google Sign up/Sign in

**Comment by priyankajayaswal** [comment]
Auth google signin happens with auth0 already: 
![image](https://user-images.githubusercontent.com/36433785/118395341-740fa080-b667-11eb-8cbe-21d5d71223cf.png)

Anything I am missing here?

**Comment by hussamkhatib** [comment]
Working fine for me as well

**Comment by souvikbasu** [comment]
Closing the issue as it's already implemented
