### ISSUE TITLE
Feedback Panel: make backend call using Apollo client

### ISSUE THREAD

**Issue by souvikbasu** [shoonyatech/wallora.com#88]
This is a
[x] bug
[x] feature request
[ ] documentation change
[ ] build/deploy enhancement request

Description:
Use Apollo client to make GQL Mutation call to backend instead of React component making REST API call
Also fix the font styling issue to remove fb font size from tailwind config 

Acceptance Criteria:
[x] Use Apollo client to make GQL Mutation call to backend instead of React component making REST API call
[x] Also fix the font styling issue to remove fb font size from tailwind config 
[ ] Intergrate MSW to mock API calls

**Comment by priyankajayaswal1** [comment]
closing since WIT is already completed.
